version: '3.7'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: 'php'
    ports:
      - '9182:9000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend

  nodejs:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: 'nodejs'
    ports:
      - '3000:80'
    networks:
      - frontend

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/test.blog.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_blog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - backend

networks:
  frontend:
  backend:
